### ISSUE TITLE
TensorBoard integration

### ISSUE THREAD

**Issue by ryanjulian** [ryanjulian/rllab#10]

**Comment by ryanjulian** [comment]
openai/baselines has a nice starting point

**Comment by ryanjulian** [comment]
The goal is to allow rllab users to use TensorBoard to view the progress of their training algorithms.

https://github.com/openai/baselines/blob/master/baselines/logger.py implements the same feature.

https://github.com/ryanjulian/rllab/blob/integration/rllab/misc/logger.py#L198 already dumps all of the logged key-value (tabular) parameters to a CSV. For TensorBoard, we'd also need to log all the k-v pairs in the TensorBoard format a they do.

The OpenAI logger is quite nice, so I wouldn't really mind we rewrote our logger to mostly copy it (while keeping the API table).

**Comment by cjcchen** [comment]
Could I import tensorflow in OpenAI directly?

**Comment by ryanjulian** [comment]
You can import tensorflow in rllab directly.

**Comment by ryanjulian** [comment]
This seems broken on my end. Can you do a verification test with an algorithm and make sure it's still logging? I get no log files.

**Comment by ryanjulian** [comment]
Never mind, fixed in https://github.com/ryanjulian/rllab/commit/1f18b744ea8e623c4e3b47eb2df6dfe1b025586c
