### ISSUE TITLE
Asynchronous plotting for Theano

### ISSUE THREAD

**Issue by jonashen** [ryanjulian/rllab#111]
Issues are equivalent to TensorFlow. See #1.

**Comment by jonashen** [comment]
@ryanjulian I discovered quite an interesting bug. When I implement async plotting using multiprocessing, Ubuntu works with no issue but Mac OSX will throw a glfw-related segmentation fault. However, when I switch to multithreading, Mac OSX works with no issue but Ubuntu takes forever to load the window, if at all (the likely culprit being Python's GIL). I'll implement both by first checking which OS the current machine running the code is, and then either fire up a thread or process accordingly.

**Comment by jonashen** [comment]
[PR](https://github.com/ryanjulian/rllab/pull/124)

**Comment by ryanjulian** [comment]
Great debugging. SGTM
