### ISSUE TITLE
Asynchronous TensorFlow plotting doesn't work on Mac OSX

### ISSUE THREAD

**Issue by jonashen** [ryanjulian/rllab#127]
Asynchronous plotting for TensorFlow works perfectly fine on Linux using `threading.Thread`, but Mac OS X will not display a window, even if `threading.Thread` is switched to `multiprocessing.Process`, which is how it was implemented using Theano.

**Comment by ryanjulian** [comment]
See https://github.com/rlworkgroup/garage/issues/3
