### ISSUE TITLE
Upgrade mujoco-py to 1.5+

### ISSUE THREAD

**Issue by ryanjulian** [ryanjulian/rllab#4]
OpenAI maintains a python binding to the MuJoCo physics engine called [mujoco-py](https://github.com/openai/mujoco-py). This library is a major dependency to rllab. Currently rllab uses an old, custom version of mujoco-py (0.5.7). [This was done](https://github.com/rll/rllab/pull/191) to avoid fixing small API changes between version upgrades to mujoco-py, but has also lead to rllab drifting away from the latest mujoco-py API and features.

This task is to add the latest version of `mujoco-py` to the rllab `conda` environment, and eliminate the older custom version (`rllab.mujoco_py`). We would also like to eliminate the special setup step of copying binaries to the `vendor/mujoco` directory (see `rllab/scripts/setup_mujoco.py`), and instead just use MuJoCo in its default install location (which is ~/.mujoco). There are breaking API changes from 0.5.7 to 1.5+, so this will require some refactoring and _thorough_ testing.

Consider this a professional software engineering task, and provide a high-quality solution which does not break existing users, minimizes change, and is stable. It is your responsibility to ensure that your changes work for all rllab use cases, and install and work seamlessly from a clean system image. Test thoroughly and provide evidence of your testing (actual unit tests in `tests/` are best, but not required). You must update all parts of the rllab codebase affected by your change. Please always use [PEP8](https://www.python.org/dev/peps/pep-0008/) style in your code, and format it using [YAPF](https://github.com/google/yapf) (with the PEP8 setting). Submit your pull request against the `master` branch of this repository.

Some notes:
* For MuJoCo you will need a freely-available personal license from the MuJoCo website. You should apply for one right away, since it takes a couple of days to get approved.
* Environments which use MuJoCo can be found in `rllab/envs/mujoco`. There is also a unit test in `tests/envs/test_envs.py`, but it should not be considered a complete test.
* There are a couple bug fix commits (https://github.com/ryanjulian/rllab/commit/3ae055a5c09cd2b87720bb87a7c9f79777797e74 and https://github.com/ryanjulian/rllab/commit/6b7f6fb32782e50f3c2b33406e2bdce03e9a65f7) on my private fork which get around flaws in mujoco-py 0.5.7. You should investigate and conclude whether these are still necessary with the new version.
* You can find examples of how to launch rllab in [examples](https://github.com/ryanjulian/rllab/tree/integration/examples) and [sandbox/rocky/tf/launchers](https://github.com/ryanjulian/rllab/tree/integration/sandbox/rocky/tf/launchers). Note that everything must run using the `run_experiment_lite` wrapper with `n_parallel` > 1, which can change the execution behavior slightly. Test thoroughly and provide ei
* rllab currently has two parallel implementation of the neural network portions of the library. The original is written in Theano and is found in `rllab/`. The tree `sandbox/rocky/tf` re-implements classes from the original tree using TensorFlow, and is backwards-compatible with the Theano tree. We are working towards using only one NN library soon, but for now your implementation needs to work in both trees.
* rllab is an upstream dependency to many projects, so it is important we do not break the existing APIs. Adding to APIs is fine as long as there is a good reason.

**Comment by ryanjulian** [comment]
Note that the manual installation from source right now is a bit of a crutch and adds a lot of complexity. It should be installed using conda/pip.

**Comment by ryanjulian** [comment]
See https://github.com/openai/gym/issues/638

**Comment by jonashen** [comment]
Let me know if my [pull request](https://github.com/ryanjulian/rllab/pull/55) has any issues.
