### ISSUE TITLE
Normalization for gym envs

### ISSUE THREAD

**Issue by eric-heiden** [ryanjulian/rllab#64]
Now that we are using OpenAI gym directly in our RL algorithms, we still need to normalize the environment (actions, observations, rewards) as in https://github.com/ryanjulian/rllab/blob/integration/rllab/envs/normalized_env.py.

So implement `NormalizedEnv` for `gym.Env`.

**Comment by jonashen** [comment]
PR [here](https://github.com/ryanjulian/rllab/pull/125)

**Comment by ryanjulian** [comment]
See https://github.com/rlworkgroup/garage/issues/13
