### ISSUE TITLE
Upgrade TensorFlow to 1.5.0+

### ISSUE THREAD

**Issue by ryanjulian** [ryanjulian/rllab#9]
Not sure if there are breaking API changes.

**Comment by zhanpenghe** [comment]
I think it is better if we can get tensorflow-gpu and cpu version synchronized and make priority for gpu. Currently the tensorflow-gpu version is 1.0.1 and the tensorflow cpu version is 1.8.0. When we import tensorflow, i think python just import the higher version so gpu will never get to work for now.

**Comment by ryanjulian** [comment]
Yes definitely. CPU and GPU version should be synchronized. GPU should have priority, but some systems have only CPU (and we need to support that).

**Comment by ghost** [comment]
Doing a quick package search I found that version 1.8 is available for both CPU and GPU releases:
![tf_versions](https://user-images.githubusercontent.com/35857569/39544204-2ecb8320-4e02-11e8-96e0-3c053fca3464.PNG)
I will update the GPU package to 1.8 in my working area to verify nothing gets broken. @ryanjulian @zhanpenghe, are there any specific tests I should run?

**Comment by ghost** [comment]
Closed with (#59)
