### ISSUE TITLE
'import glfw' after 'import mujoco_py' is an unnatural constraint

### ISSUE THREAD

**Issue by jonashen** [ryanjulian/rllab#98]
Reference: https://github.com/openai/mujoco-py/blob/6ac6ac203a875ef35b1505827264cadccbfd9f05/mujoco_py/builder.py#L61

Find a way to import the mujoco-py glfw rllab-wide without needing to resort to odd import ordering constraints.

**Comment by ryanjulian** [comment]
See https://github.com/rlworkgroup/garage/issues/10
